development:

  adapter: postgresql

  database: mydb_as_inormoc

  pool: 5

  timeout: 5000
  
  username: postgres

  password: 1234

test:

  adapter: postgresql

  database: mydb_as_inormoc

  pool: 5

  timeout: 5000

  username: postgres

  password: 1234

production:

  adapter: postgresql

  encoding: unicode

  pool: 5%